version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm --filter demo run dev
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 