apiVersion: v1
kind: Service
metadata:
  name: fintech-frontend
  labels:
    app: fintech-frontend
spec:
  selector:
    app: fintech-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fintech-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - fintech-frontend.example.com
    secretName: fintech-frontend-tls
  rules:
  - host: fintech-frontend.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fintech-frontend
            port:
              number: 80 