name: CI/CD Pipeline

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'
    
    - name: Install pnpm
      run: npm install -g pnpm
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Run tests
      run: pnpm --filter demo run test
    
    - name: Build
      run: pnpm --filter demo run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: packages/demo/dist

  trigger-jenkins:
    needs: build-and-test
    if: github.event_name == 'test'
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Jenkins job
      run: |
        curl -X POST \
          -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"parameter": [{"name":"BRANCH_NAME", "value":"${{ github.ref_name }}"}, {"name":"COMMIT_SHA", "value":"${{ github.sha }}"}]}' \
          "${{ secrets.JENKINS_URL }}/job/${{ secrets.JENKINS_JOB_NAME }}/build?token=${{ secrets.JENKINS_API_TOKEN }}" 